### ISSUE TITLE
Cube Rails Revenue trackers - changing the North-South orientation of the tracker?

### ISSUE THREAD

**Issue by LupoLoopy** [goldencow2/18Engine#4]
![image](https://user-images.githubusercontent.com/106191/94137599-8b8ee480-fe5e-11ea-8175-dfb11baa3863.png)
Seeking advice. Any help gratefully received? How would I adjust the code to accommodate a revenue tracker which works bottom to top, instead of top to bottom?

Walking through the various functions and I am struggling to wrap my head around it. An example to get me started would be so helpful!

**Comment by goldencow2** [comment]
Fixed with 2.9
