### ISSUE TITLE
When doing a reverse pay half (i.e., pay half on -50), the rounding is incorrect.

### ISSUE THREAD

**Issue by Breich90** [goldencow2/18Engine#5]
In example: 1822MX, pay half on 70.  Shareholders get paid 40, company gets 30.  Paying half on -70 means the company gets -40 and the shareholders get -30.  The rounding calc should be some form of absolute value, I'm poking through the codebase to find the payout button and I'll send in a merge request if I find it.

**Comment by goldencow2** [comment]
Fixed in version 2.84, though I will ping the mod maker.
